// MoodSync — Pipeline Orchestrator
// Ties together LLM anchors → Spotify search → de-dup → playlist assembly

import { generateAnchors, MoodAnchors } from './llm';
import * as spotify from './spotify';
import { SpotifyTrackItem } from './spotify';

export interface PipelineResult {
  moodText: string;
  anchors: MoodAnchors;
  tracks: SpotifyTrackItem[];
  playlist: {
    id: string;
    url: string;
    trackCount: number;
  };
}

function getTimeOfDay(): string {
  const hour = new Date().getHours();
  if (hour < 5) return 'late night';
  if (hour < 12) return 'morning';
  if (hour < 17) return 'afternoon';
  if (hour < 21) return 'evening';
  return 'night';
}

/**
 * Run the full mood-to-playlist pipeline (Master Blueprint Section 8)
 */
export async function runPipeline(
  accessToken: string,
  spotifyUserId: string,
  moodText: string
): Promise<PipelineResult> {
  const timeOfDay = getTimeOfDay();

  // 1. Fetch user top artists optionally for personalization context
  let topArtists: string[] = [];
  try {
    topArtists = await spotify.getTopArtists(accessToken, 5);
  } catch {
    // Top artists is an optional enhancement; continue if not available
  }

  // 2. Generate structured musical anchors from natural language mood
  const anchors = await generateAnchors(moodText, { timeOfDay, topArtists });

  // 3. Build diverse Spotify search queries from anchor dimensions
  const searchQueries: string[] = [];

  // Query 1: The user's direct intent / mood phrase
  searchQueries.push(moodText.trim());

  // Era filter if present
  let eraFilter = '';
  if (anchors.era) {
    if (anchors.era.includes('80')) eraFilter = 'year:1980-1989';
    else if (anchors.era.includes('90')) eraFilter = 'year:1990-1999';
    else if (anchors.era.includes('2000')) eraFilter = 'year:2000-2009';
    else if (anchors.era.includes('2010')) eraFilter = 'year:2010-2019';
    else if (anchors.era.includes('2020')) eraFilter = 'year:2020-2026';
  }

  // Query 2: Artist queries with era filter
  for (const artist of anchors.artists.slice(0, 4)) {
    const artistClean = artist.replace(/"/g, '').trim();
    if (eraFilter) {
      searchQueries.push(`artist:"${artistClean}" ${eraFilter}`);
    } else {
      searchQueries.push(`artist:"${artistClean}"`);
    }
  }

  // Query 3: Genre + Era natural queries (natural text matching, avoids broken genre:"" tags)
  for (const genre of anchors.genres.slice(0, 2)) {
    const genreClean = genre.replace(/"/g, '').trim();
    if (anchors.era) {
      searchQueries.push(`${genreClean} ${anchors.era}`);
    } else {
      searchQueries.push(genreClean);
    }
  }

  // Query 4: Keyword / vibe queries
  if (anchors.mood_keywords.length > 0) {
    const combinedKeywords = anchors.mood_keywords.slice(0, 2).join(' ');
    searchQueries.push(`${anchors.genres[0] || ''} ${combinedKeywords}`.trim());
  }

  // 4. Execute search queries in parallel against Spotify Web API
  const queryPromises = searchQueries.map(async (q) => {
    try {
      return await spotify.searchTracks(accessToken, q, 10);
    } catch {
      return [];
    }
  });

  const queryResults = await Promise.all(queryPromises);

  // Fallback broad search if specific queries returned very few results
  let allCandidates = queryResults.flat();
  if (allCandidates.length < 5) {
    try {
      const fallbackQuery = `${anchors.genres[0] || 'indie'} ${anchors.mood_keywords[0] || 'mood'}`;
      const fallbackTracks = await spotify.searchTracks(accessToken, fallbackQuery, 20);
      allCandidates = allCandidates.concat(fallbackTracks);
    } catch {
      // Continue with what we have
    }
  }

  // 5. De-duplicate and rank
  const seenUris = new Set<string>();
  const seenNames = new Set<string>();
  const finalTracks: SpotifyTrackItem[] = [];

  for (const track of allCandidates) {
    if (!track.uri || seenUris.has(track.uri)) continue;

    // Normalise name to avoid duplicate live/remaster versions
    const normalizedName = track.name.toLowerCase().replace(/[-–(].*$/, '').trim();
    const artistKey = `${normalizedName}|${track.artist.toLowerCase()}`;
    if (seenNames.has(artistKey)) continue;

    seenUris.add(track.uri);
    seenNames.add(artistKey);
    finalTracks.push(track);

    if (finalTracks.length >= 20) break;
  }

  if (finalTracks.length === 0) {
    throw new Error('No tracks found matching your mood. Try phrasing it with different keywords.');
  }

  // 6. Assemble Playlist on Spotify
  const trimmedMood = moodText.length > 40 ? `${moodText.substring(0, 37)}...` : moodText;
  const playlistName = `MoodSync: ${trimmedMood}`;
  const playlistDescription = `Vibe: "${moodText}" • Genres: ${anchors.genres.join(', ')} • Generated by MoodSync`;

  const playlist = await spotify.createPlaylist(
    accessToken,
    spotifyUserId,
    playlistName,
    playlistDescription
  );

  const trackUris = finalTracks.map((t) => t.uri);
  await spotify.addTracksToPlaylist(accessToken, playlist.id, trackUris);

  return {
    moodText,
    anchors,
    tracks: finalTracks,
    playlist: {
      id: playlist.id,
      url: playlist.url,
      trackCount: finalTracks.length,
    },
  };
}
